### ISSUE TITLE
Leak in movie-lens

### ISSUE THREAD

**Issue by ceresek** [renaissance-benchmarks/renaissance#187]
When executing, movie-lens disk usage grows continuously (on my machine at around 1GB per hour). This is not exactly terrible but in some situations may lead to disk full exceptions in long executions.

Filled for 47fd9ce8028ebb12f62fe18d5ea3c30f61faacee.

**Comment by axel22** [comment]
I think that @vext01 mentioned that he noticed something similar on `movie-lens` - I let him confirm.

**Comment by vext01** [comment]
We ran out of memory, not disk:

```
[2019-07-10 12:28:11: INFO] stderr: java.lang.OutOfMemoryError: Java heap space
[2019-07-10 12:28:11: INFO] stderr: 19/07/10 12:28:11 ERROR ContextCleaner: Error cleaning broadcast 780723
[2019-07-10 12:28:11: INFO] stderr: org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [120 seconds]. This timeout is controlled by spark.rpc.askTimeout
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:48)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:63)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:59)
[2019-07-10 12:28:11: INFO] stderr: 	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:83)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.storage.BlockManagerMaster.removeBroadcast(BlockManagerMaster.scala:143)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.broadcast.TorrentBroadcast$.unpersist(TorrentBroadcast.scala:267)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.broadcast.TorrentBroadcastFactory.unbroadcast(TorrentBroadcastFactory.scala:45)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.broadcast.BroadcastManager.unbroadcast(BroadcastManager.scala:60)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.ContextCleaner.doCleanupBroadcast(ContextCleaner.scala:232)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.ContextCleaner$$anonfun$org$apache$spark$ContextCleaner$$keepCleaning$1$$anonfun$apply$mcV$sp$2.apply(ContextCleaner.scala:188)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.ContextCleaner$$anonfun$org$apache$spark$ContextCleaner$$keepCleaning$1$$anonfun$apply$mcV$sp$2.apply(ContextCleaner.scala:179)
[2019-07-10 12:28:11: INFO] stderr: 	at scala.Option.foreach(Option.scala:257)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.ContextCleaner$$anonfun$org$apache$spark$ContextCleaner$$keepCleaning$1.apply$mcV$sp(ContextCleaner.scala:179)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1229)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.ContextCleaner.org$apache$spark$ContextCleaner$$keepCleaning(ContextCleaner.scala:172)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.ContextCleaner$$anon$1.run(ContextCleaner.scala:67)
[2019-07-10 12:28:11: INFO] stderr: Caused by: java.util.concurrent.TimeoutException: Futures timed out after [120 seconds]
[2019-07-10 12:28:11: INFO] stderr: 	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[2019-07-10 12:28:11: INFO] stderr: 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[2019-07-10 12:28:11: INFO] stderr: 	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[2019-07-10 12:28:11: INFO] stderr: 	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[2019-07-10 12:28:11: INFO] stderr: 	at scala.concurrent.Await$.result(package.scala:190)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:81)
[2019-07-10 12:28:11: INFO] stderr: 	... 12 more
[2019-07-10 12:28:23: INFO] stderr: 19/07/10 12:28:23 ERROR TaskSetManager: Task 1 in stage 2553648.0 failed 1 times; aborting job
[2019-07-10 12:28:23: INFO] stderr: 19/07/10 12:28:23 ERROR SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker-564,5,main]
[2019-07-10 12:28:23: INFO] stderr: java.lang.OutOfMemoryError: Java heap space
```

(Note that's our benchmark runner wrapping your benchmark, hence the `INFO` stuff).

That's running with 2000 iterations with `-Xms12G -Xmx12G` and then a 18GiB heap ulimit.

I'm guessing you have a memory leak?

**Comment by ceresek** [comment]
Although my runs used similar heap settings, I was executing with somewhat restricted storage space so hit the IOException first (around 250ish iteration). Could well be the memory leak is there too.

**Comment by ceresek** [comment]
Also, the repetition time is gradually increasing.

![samples-scatter-movie-lens](https://user-images.githubusercontent.com/6158703/61625090-382d6f00-ac7a-11e9-9bd5-84da0b39f7c0.png)

**Comment by vext01** [comment]
I also spotted:
```
19/07/12 01:39:44 ERROR LiveListenerBus: Dropping SparkListenerEvent because no remaining room in event queue. This likely means one of the SparkListeners is too slow and cannot keep up with the rate at which tasks are being started by the scheduler.
```

**Comment by farquet** [comment]
@ceresek from your latest measurements, do you still see this gradually degrading performance and the increasing disk usage ?
I hope that #227 fixed it, so I'm closing this issue. Feel free to reopen if you still see the problem.

**Comment by ceresek** [comment]
Yes, looks fixed (tested on both OpenJDK 8 and 11).
