### ISSUE TITLE
finagle-chirper crashes if a network interface is not up.

### ISSUE THREAD

**Issue by vext01** [renaissance-benchmarks/renaissance#188]
Hi,

I promised @axel22 that I'd file information about this crash.

Our benchmark runner disables the network cards of the system to avoid network traffic interrupts from interfering with benchmark measurements.

Here is a log from our runner showing finagle-chirper crashing if there is no upped interface:
```
[2019-06-28 16:58:59: INFO] Next execution is 'finagle-chirper(0)' (default-ext variant) under 'graal-ce'
[2019-06-28 16:58:59: INFO] Estimated completion (next execution): 2019-06-28 17:25:05 (0:26:06 from now)
[2019-06-28 16:58:59: INFO] Reboot in preparation for next execution
[2019-06-28 17:03:10: INFO] stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[2019-06-28 17:03:10: INFO] stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
[2019-06-28 17:03:10: INFO] stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[2019-06-28 17:03:10: INFO] stderr: Jun 28, 2019 5:03:10 PM com.twitter.finagle.Init$$anonfun$6 apply$mcV$sp
[2019-06-28 17:03:10: INFO] stderr: INFO: Finagle version 19.4.0 (rev=15ae0aba979a2c11ed4a71774b2e995f5df918b4) built at 20190418-114039
[2019-06-28 17:03:10: INFO] stderr: Jun 28, 2019 5:03:10 PM io.netty.util.internal.MacAddressUtil defaultMachineId
[2019-06-28 17:03:10: INFO] stderr: WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 92:ba:45:50:af:9b:58:fd
[2019-06-28 17:03:10: INFO] stderr: Master port: 42009
[2019-06-28 17:03:10: INFO] stderr: Cache ports: 33787, 43845, 43673, 46449
[2019-06-28 17:03:10: INFO] stderr: ====== finagle-chirper (twitter-finagle), iteration 0 started ======
[2019-06-28 17:03:11: INFO] stderr: Exception occurred in org.renaissance.twitter.finagle.FinagleChirper@b1534d3: connection timed out: localhost/127.0.0.1:42009 at remote address: localhost/127.0.0.1:42009. Remote Info: Not Available
[2019-06-28 17:03:11: INFO] stderr: Failure(connection timed out: localhost/127.0.0.1:42009 at remote address: localhost/127.0.0.1:42009. Remote Info: Not Available, flags=0x08) with RemoteInfo -> Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: localhost/127.0.0.1:42009, Downstream label: :42009, Trace Id: 7cdd482f5db2b235.7cdd482f5db2b235<:7cdd482f5db2b235 with Service -> :42009
[2019-06-28 17:03:11: INFO] stderr: Caused by: com.twitter.finagle.ConnectionFailedException: connection timed out: localhost/127.0.0.1:42009 at remote address: localhost/127.0.0.1:42009. Remote Info: Not Available
[2019-06-28 17:03:11: INFO] stderr:     at com.twitter.finagle.netty4.ConnectionBuilder$$anon$1.operationComplete(ConnectionBuilder.scala:99)
[2019-06-28 17:03:11: INFO] stderr:     at com.twitter.finagle.netty4.ConnectionBuilder$$anon$1.operationComplete(ConnectionBuilder.scala:78)
[2019-06-28 17:03:11: INFO] stderr:     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
[2019-06-28 17:03:11: INFO] stderr:     at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
[2019-06-28 17:03:11: INFO] stderr:     at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
[2019-06-28 17:03:11: INFO] stderr:     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
[2019-06-28 17:03:11: INFO] stderr:     at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
[2019-06-28 17:03:11: INFO] stderr:     at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:570)
[2019-06-28 17:03:11: INFO] stderr:     at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
[2019-06-28 17:03:11: INFO] stderr:     at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
[2019-06-28 17:03:11: INFO] stderr:     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[2019-06-28 17:03:11: INFO] stderr:     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[2019-06-28 17:03:11: INFO] stderr:     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:335)
[2019-06-28 17:03:11: INFO] stderr:     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
[2019-06-28 17:03:11: INFO] stderr:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2019-06-28 17:03:11: INFO] stderr:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2019-06-28 17:03:11: INFO] stderr:     at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23)
[2019-06-28 17:03:11: INFO] stderr:     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2019-06-28 17:03:11: INFO] stderr:     at java.lang.Thread.run(Thread.java:748)
[2019-06-28 17:03:11: INFO] stderr: Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: localhost/127.0.0.1:42009
[2019-06-28 17:03:11: INFO] stderr:     at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:568)
[2019-06-28 17:03:11: INFO] stderr:     ... 11 more
```

Thanks

**Comment by vhotspur** [comment]
> Our benchmark runner disables the network cards of the system to avoid network traffic interrupts from interfering with benchmark measurements.
> 
> Here is a log from our runner showing finagle-chirper crashing if there is no upped interface:
> 
> ```
> ...
> [2019-06-28 17:03:11: INFO] stderr: Caused by: \
>   com.twitter.finagle.ConnectionFailedException: \
>   connection timed out: localhost/127.0.0.1:42009 \
>   at remote address: localhost/127.0.0.1:42009. \
>   Remote Info: Not Available
> ...
> ```

Looking at the error messages, this seems to indicate that loopback interface was down. Is that so or the message is misleading in this sense? Because if loopback was really down (together with normal interfaces), I believe this benchmark will not be able to function properly as it internally starts a web server listening on first available interface...

**Comment by vext01** [comment]
I used `ifdown -a` on a Debian 9 system, which claims to take down `auto` interfaces listed under `/etc/network/interfaces`.

I've just experimented. On a machine with the following `/etc/network/interfaces` file:
```
auto lo
iface lo inet loopback
```

Before `ifdown -a` I can ping loopback, after I cannot!

I'm surprised that there is the option to down the loopback interface! When would you want that! :P

Closing, as clearly this is not your bug, it's ours!
