### ISSUE TITLE
page-rank emits network errors on teardown if the network card is disabled.

### ISSUE THREAD

**Issue by vext01** [renaissance-benchmarks/renaissance#189]
Here's a log from running the benchmark under our runner:
```
...
[2019-07-10 19:38:55: INFO] stderr: ====== page-rank (apache-spark), iteration 1998 completed (3100.506 ms) ======
[2019-07-10 19:38:55: INFO] stderr: ====== page-rank (apache-spark), final iteration started ======
[2019-07-10 19:38:58: INFO] stderr: ====== page-rank (apache-spark), final iteration completed (3185.671 ms) ======
[2019-07-10 19:40:58: INFO] stderr: 19/07/10 19:40:58 ERROR RetryingBlockFetcher: Exception while beginning fetch of 1 outstanding blocks
[2019-07-10 19:40:58: INFO] stderr: java.io.IOException: Connecting to /127.0.1.1:35551 timed out (120000 ms)
[2019-07-10 19:40:58: INFO] stderr:     at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:225)
[2019-07-10 19:40:58: INFO] stderr:     at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:179)
[2019-07-10 19:40:58: INFO] stderr:     at org.apache.spark.network.netty.NettyBlockTransferService$$anon$1.createAndStart(NettyBlockTransferService.scala:96)
[2019-07-10 19:40:58: INFO] stderr:     at org.apache.spark.network.shuffle.RetryingBlockFetcher.fetchAllOutstanding(RetryingBlockFetcher.java:140)
[2019-07-10 19:40:58: INFO] stderr:     at org.apache.spark.network.shuffle.RetryingBlockFetcher.start(RetryingBlockFetcher.java:120)
[2019-07-10 19:40:58: INFO] stderr:     at org.apache.spark.network.netty.NettyBlockTransferService.fetchBlocks(NettyBlockTransferService.scala:105)
[2019-07-10 19:40:58: INFO] stderr:     at org.apache.spark.network.BlockTransferService.fetchBlockSync(BlockTransferService.scala:92)
[2019-07-10 19:40:58: INFO] stderr:     at org.apache.spark.storage.BlockManager.getRemoteBytes(BlockManager.scala:554)
[2019-07-10 19:40:58: INFO] stderr:     at org.apache.spark.scheduler.TaskResultGetter$$anon$2$$anonfun$run$1.apply$mcV$sp(TaskResultGetter.scala:76)
[2019-07-10 19:40:58: INFO] stderr:     at org.apache.spark.scheduler.TaskResultGetter$$anon$2$$anonfun$run$1.apply(TaskResultGetter.scala:57)
[2019-07-10 19:40:58: INFO] stderr:     at org.apache.spark.scheduler.TaskResultGetter$$anon$2$$anonfun$run$1.apply(TaskResultGetter.scala:57)
[2019-07-10 19:40:58: INFO] stderr:     at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1857)
[2019-07-10 19:40:58: INFO] stderr:     at org.apache.spark.scheduler.TaskResultGetter$$anon$2.run(TaskResultGetter.scala:56)
[2019-07-10 19:40:58: INFO] stderr:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2019-07-10 19:40:58: INFO] stderr:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2019-07-10 19:40:58: INFO] stderr:     at java.lang.Thread.run(Thread.java:748)
[2019-07-10 19:42:58: INFO] stderr: 19/07/10 19:42:58 ERROR RetryingBlockFetcher: Exception while beginning fetch of 1 outstanding blocks
[2019-07-10 19:42:58: INFO] stderr: java.io.IOException: Connecting to /127.0.1.1:35551 timed out (120000 ms)
[2019-07-10 19:42:58: INFO] stderr:     at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:225)
[2019-07-10 19:42:58: INFO] stderr:     at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:179)
[2019-07-10 19:42:58: INFO] stderr:     at org.apache.spark.network.netty.NettyBlockTransferService$$anon$1.createAndStart(NettyBlockTransferService.scala:96)
[2019-07-10 19:42:58: INFO] stderr:     at org.apache.spark.network.shuffle.RetryingBlockFetcher.fetchAllOutstanding(RetryingBlockFetcher.java:140)
[2019-07-10 19:42:58: INFO] stderr:     at org.apache.spark.network.shuffle.RetryingBlockFetcher.start(RetryingBlockFetcher.java:120)
[2019-07-10 19:42:58: INFO] stderr:     at org.apache.spark.network.netty.NettyBlockTransferService.fetchBlocks(NettyBlockTransferService.scala:105)
[2019-07-10 19:42:58: INFO] stderr:     at org.apache.spark.network.BlockTransferService.fetchBlockSync(BlockTransferService.scala:92)
[2019-07-10 19:42:58: INFO] stderr:     at org.apache.spark.storage.BlockManager.getRemoteBytes(BlockManager.scala:554)
[2019-07-10 19:42:58: INFO] stderr:     at org.apache.spark.scheduler.TaskResultGetter$$anon$2$$anonfun$run$1.apply$mcV$sp(TaskResultGetter.scala:76)
[2019-07-10 19:42:58: INFO] stderr:     at org.apache.spark.scheduler.TaskResultGetter$$anon$2$$anonfun$run$1.apply(TaskResultGetter.scala:57)
[2019-07-10 19:42:58: INFO] stderr:     at org.apache.spark.scheduler.TaskResultGetter$$anon$2$$anonfun$run$1.apply(TaskResultGetter.scala:57)
[2019-07-10 19:42:58: INFO] stderr:     at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1857)
[2019-07-10 19:42:58: INFO] stderr:     at org.apache.spark.scheduler.TaskResultGetter$$anon$2.run(TaskResultGetter.scala:56)
[2019-07-10 19:42:58: INFO] stderr:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2019-07-10 19:42:58: INFO] stderr:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2019-07-10 19:42:58: INFO] stderr:     at java.lang.Thread.run(Thread.java:748)
[2019-07-10 19:44:58: INFO] stderr: 19/07/10 19:44:58 ERROR RetryingBlockFetcher: Exception while beginning fetch of 1 outstanding blocks
[2019-07-10 19:44:58: INFO] stderr: java.io.IOException: Connecting to /127.0.1.1:35551 timed out (120000 ms)
...
```

At first I thought `127.0.1.1` (not `127.0.0.1`) was a bug, but apparently that's an alias for loopback:
https://serverfault.com/questions/363095/why-does-my-hostname-appear-with-the-address-127-0-1-1-rather-than-127-0-0-1-in

**Comment by vext01** [comment]
This likely has the same conclusion as #188, closing.
