### ISSUE TITLE
db-shootout fails on ppc64_aix & ppc64le_linux

### ISSUE THREAD

**Issue by piyush286** [renaissance-benchmarks/renaissance#210]
### Problem Description

Getting the following errors while running `db-shootout` on Power. I've just tried ppc64_aix & ppc64le_linux platforms on Power. I haven't tested other power platforms, but I believe they should fail as well. The benchmark works fine on other platforms that I've tested such as zLinux, xLinux and Windows.

It fails with both HotSpot and OpenJ9.

### Errors

```
13:33:45  java.lang.NullPointerException
13:33:45  	at org.lmdbjava.bench.LevelDb$CommonLevelDb.teardown(LevelDb.java:128)
13:33:45  	at org.lmdbjava.bench.LevelDb$Reader.teardown(LevelDb.java:233)
13:33:45  	at org.renaissance.database.DbShootout.tearDownAfterAll(DbShootout.scala:80)
13:33:45  	at org.renaissance.RenaissanceBenchmark.runBenchmark(RenaissanceBenchmark.java:97)
13:33:45  	at org.renaissance.RenaissanceSuite$.$anonfun$main$2(renaissance-suite.scala:308)
13:33:45  	at org.renaissance.RenaissanceSuite$.$anonfun$main$2$adapted(renaissance-suite.scala:306)
13:33:45  	at org.renaissance.RenaissanceSuite$$$Lambda$93.0000000000000000.apply(Unknown Source)
13:33:45  	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
13:33:45  	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
13:33:45  	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
13:33:45  	at org.renaissance.RenaissanceSuite$.main(renaissance-suite.scala:306)
13:33:45  	at org.renaissance.RenaissanceSuite.main(renaissance-suite.scala)
13:33:45  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:33:45  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:33:45  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:33:45  	at java.lang.reflect.Method.invoke(Method.java:498)
13:33:45  	at org.renaissance.Launcher.main(Launcher.java:18)
13:33:45  Exception occurred in org.renaissance.database.DbShootout@5b0ec81a: Could not load library. Reasons: [leveldbjni64-1.8 (Not found in java.library.path), leveldbjni-1.8 (Not found in java.library.path), leveldbjni (Not found in java.library.path)]
13:33:45  java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [leveldbjni64-1.8 (Not found in java.library.path), leveldbjni-1.8 (Not found in java.library.path), leveldbjni (Not found in java.library.path)]
13:33:45  	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:187)
13:33:45  	at org.fusesource.hawtjni.runtime.Library.load(Library.java:143)
13:33:45  	at org.fusesource.leveldbjni.JniDBFactory.<clinit>(JniDBFactory.java:48)
13:33:45  	at org.lmdbjava.bench.LevelDb$CommonLevelDb.setup(LevelDb.java:118)
13:33:45  	at org.lmdbjava.bench.LevelDb$Reader.setup(LevelDb.java:227)
13:33:45  	at org.renaissance.database.DbShootout.setUpBeforeAll(DbShootout.scala:62)
13:33:45  	at org.renaissance.RenaissanceBenchmark.runBenchmark(RenaissanceBenchmark.java:74)
13:33:45  	at org.renaissance.RenaissanceSuite$.$anonfun$main$2(renaissance-suite.scala:308)
13:33:45  	at org.renaissance.RenaissanceSuite$.$anonfun$main$2$adapted(renaissance-suite.scala:306)
13:33:45  	at org.renaissance.RenaissanceSuite$$$Lambda$93.0000000000000000.apply(Unknown Source)
13:33:45  	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
13:33:45  	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
13:33:45  	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
13:33:45  	at org.renaissance.RenaissanceSuite$.main(renaissance-suite.scala:306)
13:33:45  	at org.renaissance.RenaissanceSuite.main(renaissance-suite.scala)
13:33:45  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:33:45  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:33:45  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:33:45  	at java.lang.reflect.Method.invoke(Method.java:498)
13:33:45  	at org.renaissance.Launcher.main(Launcher.java:18)
13:33:45  The following benchmarks failed: db-shootout
13:33:45  
13:33:45  db-shootout_0_FAILED

```

### To Produce
- Direct command to run the benchmark
OR
1. Add (or enable if it already exists) the target(s) in the Renaissance playlist (https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/perf/renaissance/playlist.xml)
2. Use the Adopt Grinder: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/build?delay=0sec if you have permissions or else, run locally 
3. Set the `TARGET` to the relevant benchmark

**Comment by farquet** [comment]
Thanks @piyush286 for the report !
This issue has already been reported at #153. So I'll close this issue as a duplicate. There is an agreement there to remove the `LevelDB` dependency completely (which contains native dependencies but not for all platforms).

**Comment by piyush286** [comment]
I notice #153 occurs on zLinux besides pLinux, but I could run this benchmark successfully on zLinux. Not sure if that's an intermittent issue.
