### ISSUE TITLE
Error while trying to output JSON file at the end of the benchmark on W10 20H2 (19042.804) with OpenJDK 11

### ISSUE THREAD

**Issue by dcominottim** [renaissance-benchmarks/renaissance#236]
The command

`java -jar renaissance-gpl-0.11.0.jar --csv results.csv --json results.json all`

with 

- W10 20H2 (19042.804)
- openjdk 11.0.8 2020-07-14 LTS (RedHat)

fails after the jdk-streams test with

```
====== scrabble (jdk-streams) [default], iteration 49 completed (146.549 ms) ======
21/02/23 13:16:53 ERROR main: Harness failed with exception: scala.MatchError: com.sun.management.internal.OperatingSystemImpl@37c1cfa (of class com.sun.management.internal.OperatingSystemImpl)
        at org.renaissance.harness.JsonWriter.getOsInfo(ResultWriter.scala:168)
        at org.renaissance.harness.JsonWriter.getEnvironment(ResultWriter.scala:152)
        at org.renaissance.harness.JsonWriter.store(ResultWriter.scala:349)
        at org.renaissance.harness.ResultWriter.org$renaissance$harness$ResultWriter$$storeResults(ResultWriter.scala:60)
        at org.renaissance.harness.ResultWriter.beforeHarnessShutdown(ResultWriter.scala:64)
        at org.renaissance.harness.EventDispatcher.notifyBeforeHarnessShutdown(EventDispatcher.java:65)
        at org.renaissance.harness.RenaissanceSuite$.runBenchmarks(RenaissanceSuite.scala:141)
        at org.renaissance.harness.RenaissanceSuite$.main(RenaissanceSuite.scala:94)
        at org.renaissance.harness.RenaissanceSuite.main(RenaissanceSuite.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.renaissance.core.Launcher.launchHarnessClass(Launcher.java:37)
        at org.renaissance.core.Launcher.main(Launcher.java:25)

Feb 23, 2021 1:16:53 PM org.renaissance.core.Launcher launchHarnessClass
SEVERE: Harness failed with exception: scala.MatchError: com.sun.management.internal.OperatingSystemImpl@37c1cfa (of class com.sun.management.internal.OperatingSystemImpl)
        at org.renaissance.harness.JsonWriter.getOsInfo(ResultWriter.scala:168)
        at org.renaissance.harness.JsonWriter.getEnvironment(ResultWriter.scala:152)
        at org.renaissance.harness.JsonWriter.store(ResultWriter.scala:349)
        at org.renaissance.harness.ResultWriter.org$renaissance$harness$ResultWriter$$storeResults(ResultWriter.scala:60)
        at org.renaissance.harness.ResultWriter.beforeHarnessShutdown(ResultWriter.scala:64)
        at org.renaissance.harness.EventDispatcher.notifyBeforeHarnessShutdown(EventDispatcher.java:65)
        at org.renaissance.harness.RenaissanceSuite$.runBenchmarks(RenaissanceSuite.scala:141)
        at org.renaissance.harness.RenaissanceSuite$.main(RenaissanceSuite.scala:94)
        at org.renaissance.harness.RenaissanceSuite.main(RenaissanceSuite.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.renaissance.core.Launcher.launchHarnessClass(Launcher.java:37)
        at org.renaissance.core.Launcher.main(Launcher.java:25)
```

**Comment by lbulej** [comment]
Thank you for the report! It seems that the problem is a missing match default (see #237), but I don't have a Windows 10 machine on which I would run RedHat-built OpenJDK. Is this running in WSL?

Could you test the attached JAR/ZIP file (built from #237)? I excluded all but the `dummy` benchmarks to get under the 10MB limitation for attached files and renamed the JAR to ZIP for GitHub to accept it, but you should be able to test it simply by running the following command:

```
java -jar renaissance-gpl-0.11.0-b5d9e14-dummy.zip --csv results.csv --json results.json dummy-empty
```

[renaissance-gpl-0.11.0-b5d9e14-dummy.zip](https://github.com/renaissance-benchmarks/renaissance/files/6035574/renaissance-gpl-0.11.0-b5d9e14-dummy.zip)

**Comment by lbulej** [comment]
I'm going to merge the proposed fix, please reopen if necessary.
