### ISSUE TITLE
Cannot compile using openJDK14

### ISSUE THREAD

**Issue by underhood31** [renaissance-benchmarks/renaissance#239]
While compiling the source code with openJDK14 I am getting the following error. Is there any workaround so that openJDK14 can be used to compile this suite. 
```
rror: error while loading String, class file '/modules/java.base/java/lang/String.class' is broken
(class java.lang.NullPointerException/null)
[error] java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
[error]         at java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:176)
[error]         at scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:204)
[error]         at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$asURLs$1(AggregateClassPath.scala:55)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:937)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:937)
.
.
.
[error]         at xsbt.boot.Boot$.main(Boot.scala:18)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```
Please find the full output attached. Any help would be appreciated. 
[out.txt](https://github.com/renaissance-benchmarks/renaissance/files/6124904/out.txt)

**Comment by ceresek** [comment]
Hello, could you please try the topic/update-scala-sbt branch instead of master ?

**Comment by underhood31** [comment]
Thanks that was useful

**Comment by ceresek** [comment]
Glad it worked. Please note - the update means the benchmark scores are not necessarily the same as with the older version. @lbulej will know which benchmarks exactly were modified, if you need that (we plan to merge this branch quite soon).
