### ISSUE TITLE
Spark benchmarks fail on Windows

### ISSUE THREAD

**Issue by vhotspur** [renaissance-benchmarks/renaissance#265]
```
java.lang.Exception: Wrong winutils.exe size: expected 109568, written 112640
        at org.renaissance.apache.spark.SparkUtil.setUpHadoop(SparkUtil.scala:124)
        at org.renaissance.apache.spark.SparkUtil.setUpSparkContext(SparkUtil.scala:42)
        at org.renaissance.apache.spark.SparkUtil.setUpSparkContext$(SparkUtil.scala:38)
        at org.renaissance.apache.spark.Als.setUpSparkContext(Als.scala:50)
        at org.renaissance.apache.spark.Als.setUpBeforeAll(Als.scala:95)
        at org.renaissance.harness.ExecutionDriver.executeBenchmark(ExecutionDriver.java:59)
        at org.renaissance.harness.RenaissanceSuite$.$anonfun$runBenchmarks$1(RenaissanceSuite.scala:133)
        at org.renaissance.harness.RenaissanceSuite$.$anonfun$runBenchmarks$1$adapted(RenaissanceSuite.scala:127)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at org.renaissance.harness.RenaissanceSuite$.runBenchmarks(RenaissanceSuite.scala:127)
        at org.renaissance.harness.RenaissanceSuite$.main(RenaissanceSuite.scala:104)
        at org.renaissance.harness.RenaissanceSuite.main(RenaissanceSuite.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.renaissance.core.Launcher.loadAndInvokeHarnessClass(Launcher.java:114)
        at org.renaissance.core.Launcher.launchHarnessClass(Launcher.java:73)
        at org.renaissance.core.Launcher.main(Launcher.java:37)
```

Probably due to update of `winutils.exe` resource.

**Comment by lbulej** [comment]
You are right. I'll bump Spark and update everything.

**Comment by vhotspur** [comment]
Please, see my `issues/265` branch.

**Comment by lbulej** [comment]
Ooops, it didn't seem like there is more to do (dll loading). Care to elaborate?

**Comment by vhotspur** [comment]
Hadoop uses [native functions](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/NativeLibraries.html)  for [some operations](https://cwiki.apache.org/confluence/display/HADOOP2/WindowsProblems). Without the DLL, it fails in some clean-up phase.
