### ISSUE TITLE
Windows builds broken

### ISSUE THREAD

**Issue by vhotspur** [renaissance-benchmarks/renaissance#272]
Execution ends with the following trace:

```
[2021-06-21T02:59:16.727-0700] org.renaissance.core (org.renaissance.core.Launcher main)
SEVERE: Failed to load harness: org.renaissance.core.ModuleLoader$ModuleLoadingException: could not extract resource 'renaissance-harness\renaissance-harness_
2.13-0.11.0-252-g32aeaaf.jar' into 'C:\Users\vhotspur\renaissance-issue-265\launcher-025916-2120882362573410541\renaissance-harness\lib\renaissance-harness\re
naissance-harness_2.13-0.11.0-252-g32aeaaf.jar': resource not found
        at org.renaissance.core.ModuleLoader.extractResources(ModuleLoader.java:224)
        at org.renaissance.core.ModuleLoader.createClassLoaderForModule(ModuleLoader.java:159)
        at org.renaissance.core.Launcher.loadAndInvokeHarnessClass(Launcher.java:111)
        at org.renaissance.core.Launcher.launchHarnessClass(Launcher.java:73)
        at org.renaissance.core.Launcher.main(Launcher.java:37)
```

**Comment by ceresek** [comment]
On a related note, does `--plugin` work for you ? I've had a problem with 510b3b9 (not master branch) because it tried to use a filename as a URL, which failed, and one cannot specify the protocol on the command line because the loader uses the separator. I've solved this with a quick hack to get things running but if it also impacts master we should take a look.

**Comment by vhotspur** [comment]
> On a related note, does `--plugin` work for you ?

No (looked at  018c8e3). I will open a separate ticket.
