### ISSUE TITLE
Dotty fails in standalone mode.

### ISSUE THREAD

**Issue by farquet** [renaissance-benchmarks/renaissance#347]
```
====> dotty
Benchmark 'dotty' failed with exception:
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at org.renaissance.scala.dotty.Dotty.setUpBeforeAll(Dotty.scala:106)
	at org.renaissance.harness.ExecutionDriver.executeBenchmark(ExecutionDriver.java:82)
	at org.renaissance.harness.RenaissanceSuite$.$anonfun$runBenchmarks$1(RenaissanceSuite.scala:163)
	at org.renaissance.harness.RenaissanceSuite$.$anonfun$runBenchmarks$1$adapted(RenaissanceSuite.scala:159)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.renaissance.harness.RenaissanceSuite$.runBenchmarks(RenaissanceSuite.scala:159)
	at org.renaissance.harness.RenaissanceSuite$.main(RenaissanceSuite.scala:132)
	at org.renaissance.harness.RenaissanceSuite.main(RenaissanceSuite.scala)
The following benchmarks failed: dotty
```
@lbulej's [comment](https://github.com/renaissance-benchmarks/renaissance/pull/346#issuecomment-1023028891) on that:

> This is due to the fact that we build a class path for Dotty in the setup phase and while doing that, we assume that the class loader is the URLClassloader. It apparently isn't when the class path is defined in the manifest.

**Comment by lbulej** [comment]
Apparently, there are still JVM issues, specifically on OpenJ9, see #346
