### ISSUE TITLE
Build in Fedora 35-based container fails

### ISSUE THREAD

**Issue by vhotspur** [renaissance-benchmarks/renaissance#351]
I wanted to update our [Docker images](https://github.com/renaissance-benchmarks/docker-buildenv) to use Fedora 35 (instead of 34) and this actually lead to quite extraordinary failures.

Here is [log of one of the runs](https://github.com/renaissance-benchmarks/renaissance/runs/5010160956). Pasting here for completeness at the end of the description.

I have no idea what could be the culprit. It was not a spurious error, the JDK 10 build was failing in a very repeatable fashion. I will investigate this later on, we can still use the 34-based images. There is no difference in the images from Java perspective: except for JDK 8 (that is still pre-packaged), we install all the JDKs manually (from precompiled tarballs) and thus the only difference is in the base image itself.

It failed in the _Build base & JMH bundles_ phase (sorry for the control sequence for colors):

```text
2022-01-31T17:53:52.9274504Z ##[group]Run tools/ci/build-both.sh
2022-01-31T17:53:52.9274796Z [36;1mtools/ci/build-both.sh[0m
2022-01-31T17:53:52.9275166Z shell: bash --noprofile --norc -e -o pipefail {0}
2022-01-31T17:53:52.9275657Z ##[endgroup]
2022-01-31T17:53:53.1189400Z /__w/renaissance/renaissance /__w/renaissance/renaissance
2022-01-31T17:53:53.1193166Z + '[' -s target/renaissance-gpl-0.14.0.jar ']'
2022-01-31T17:53:53.1193833Z + ci_sbt --batch 'renaissancePackage;renaissanceJmhPackage'
2022-01-31T17:53:53.1194336Z + local TRUST_STORE=/__w/renaissance/renaissance/tools/jks/cacerts
2022-01-31T17:53:53.1195198Z + /__w/renaissance/renaissance/tools/sbt/bin/sbt -J-Djavax.net.ssl.trustStore=/__w/renaissance/renaissance/tools/jks/cacerts --batch 'renaissancePackage;renaissanceJmhPackage'
2022-01-31T17:53:53.5900432Z copying runtime jar...
2022-01-31T17:53:54.3533240Z java.util.ConcurrentModificationException
2022-01-31T17:53:54.3544592Z 	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1471)
2022-01-31T17:53:54.3545176Z 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
2022-01-31T17:53:54.3548622Z 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
2022-01-31T17:53:54.3552872Z 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169)
2022-01-31T17:53:54.3557235Z 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
2022-01-31T17:53:54.3561734Z 	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
2022-01-31T17:53:54.3565977Z 	at java.base/jdk.internal.jrtfs.JrtDirectoryStream$1.hasNext(JrtDirectoryStream.java:81)
2022-01-31T17:53:54.3569791Z 	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:348)
2022-01-31T17:53:54.3573822Z 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2752)
2022-01-31T17:53:54.3577588Z 	at xsbt.boot.IO.copyDirectory(IO.java:15)
2022-01-31T17:53:54.3581315Z 	at xsbt.boot.Launch$.exportRt(Launch.scala:62)
2022-01-31T17:53:54.3584595Z 	at xsbt.boot.Launch$.apply(Launch.scala:28)
2022-01-31T17:53:54.3585161Z 	at xsbt.boot.Launch$.apply(Launch.scala:21)
2022-01-31T17:53:54.3660506Z 	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
2022-01-31T17:53:54.3660824Z 	at xsbt.boot.Boot$.run(Boot.scala:73)
2022-01-31T17:53:54.3661077Z 	at xsbt.boot.Boot$.main(Boot.scala:21)
2022-01-31T17:53:54.3661340Z 	at xsbt.boot.Boot.main(Boot.scala)
2022-01-31T17:53:54.3661708Z [error] [launcher] error during sbt launcher: java.util.ConcurrentModificationException
2022-01-31T17:53:54.7199275Z [info] [launcher] getting org.scala-sbt sbt 1.6.1  (this may take some time)...
2022-01-31T17:53:58.9694483Z [info] [launcher] getting Scala 2.12.15 (for sbt)...
2022-01-31T17:54:00.9023621Z [0m[[0m[0minfo[0m] [0m[0mwelcome to sbt 1.6.1 (Oracle Corporation Java 10.0.2)[0m
2022-01-31T17:54:04.3882480Z [0m[[0m[0minfo[0m] [0m[0mloading settings for project renaissance-build from build.sbt,plugins.sbt ...[0m
2022-01-31T17:54:05.6054788Z [0m[[0m[0minfo[0m] [0m[0mloading project definition from /__w/renaissance/renaissance/project[0m
2022-01-31T17:54:08.3041005Z [0m[[0m[0minfo[0m] [0m[0mcompiling 14 Java sources to /__w/renaissance/renaissance/renaissance-core/target/scala-2.12/classes ...[0m
2022-01-31T17:54:10.1334147Z [0m[[0m[0minfo[0m] [0m[0mdone compiling[0m
2022-01-31T17:54:10.7430612Z [0m[[0m[0minfo[0m] [0m[0mcompiling 4 Scala sources to /__w/renaissance/renaissance/project/target/scala-2.12/sbt-1.0/classes ...[0m
2022-01-31T17:54:10.8893138Z [0m[[0m[0minfo[0m] [0m[0mNon-compiled module 'compiler-bridge_2.12' for Scala 2.12.15. Compiling...[0m
2022-01-31T17:54:22.3152406Z error: Error while emitting xsbt/ExtractUsedNames$ExtractUsedNamesTraverser
2022-01-31T17:54:22.3153372Z assertion failed: The classfile for xsbt/ExtractUsedNames$ExtractUsedNamesTraverser$PatMatDependencyTraverser$ could not be found on the compilation classpath.
2022-01-31T17:54:22.3256871Z one error found
2022-01-31T17:54:22.3315717Z [0m[[0m[0minfo[0m] [0m[0mAttempting to fetch org.scala-sbt:compiler-bridge_2.12:1.6.0.[0m
2022-01-31T17:54:22.4081439Z [0m[[0m[31merror[0m] [0m[0m(Compile / [31mcompileIncremental[0m) Error compiling the sbt component 'compiler-bridge_2.12'[0m
2022-01-31T17:54:22.4498089Z [0m[[0m[33mwarn[0m] [0m[0mProject loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)[0m
2022-01-31T17:54:22.8077957Z [0J
2022-01-31T17:54:22.8089446Z ##[error]Process completed with exit code 1.
```

**Comment by lbulej** [comment]
Interesting, it built the release on my F35 without problems (with JDK8 and JDK11). This seems to be very early on in SBT initialization stage. It would probably play with SBT versions (it should be safe to downgrade).
