### ISSUE TITLE
ConcurrentModificationException on finagle-chirper

### ISSUE THREAD

**Issue by lewurm** [renaissance-benchmarks/renaissance#354]
```
GC before operation: completed in 54.688 ms, heap usage 410.982 MB -> 34.636 MB.
[2022-02-21T16:17:56.179+0100] com.twitter.finagle.util.DefaultMonitor (com.twitter.finagle.util.DefaultMonitor logWithRemoteInfo)
WARNING: Exception propagated to the default monitor (upstream address: /127.0.0.1:56796, downstream address: n/a, label: ).

java.util.ConcurrentModificationException: mutation occurred during iteration
	at scala.collection.mutable.MutationTracker$.checkMutations(MutationTracker.scala:43)
	at scala.collection.mutable.CheckedIndexedSeqView$CheckedIterator.hasNext(CheckedIndexedSeqView.scala:47)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
	at org.renaissance.twitter.finagle.FinagleChirper$Master.$anonfun$mostRechirpsInAllFeeds$1(FinagleChirper.scala:112)
	at org.renaissance.twitter.finagle.FinagleChirper$Master.$anonfun$mostRechirpsInAllFeeds$1$adapted(FinagleChirper.scala:110)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1293)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:938)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:97)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:935)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.internal(Tasks.scala:169)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.internal$(Tasks.scala:156)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$AWSFJTWrappedTask.internal(Tasks.scala:304)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.compute(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.compute$(Tasks.scala:148)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$AWSFJTWrappedTask.compute(Tasks.scala:304)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

I see this exception roughly every 20-30 iterations on darwin-aarch64 with graal-enterprise jarGraal. It doesn't seem to affect performance.

**Comment by lewurm** [comment]
Same benchmark, but different stacktrace, again darwin-aarch64 with graal-enterprise jarGraal:
```
GC before operation: completed in 44.710 ms, heap usage 141.220 MB -> 47.934 MB.
[2022-02-21T17:25:48.194+0100] com.twitter.finagle.util.DefaultMonitor (com.twitter.finagle.util.DefaultMonitor logWithRemoteInfo)
WARNING: Exception propagated to the default monitor (upstream address: /127.0.0.1:55082, downstream address: n/a, label: ).
                                                                                                                                                                                                                      java.util.ConcurrentModificationException: mutation occurred during iteration                                                                                                                                             at scala.collection.mutable.MutationTracker$.checkMutations(MutationTracker.scala:43)
    at scala.collection.mutable.CheckedIndexedSeqView$CheckedIterator.hasNext(CheckedIndexedSeqView.scala:47)
    at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
    at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:926)                                                                                                                                                      at org.renaissance.twitter.finagle.FinagleChirper$Master.analyze(FinagleChirper.scala:58)
    at org.renaissance.twitter.finagle.FinagleChirper$Master.$anonfun$hashStartCountInAllFeeds$1(FinagleChirper.scala:84)                                                                                                 at org.renaissance.twitter.finagle.FinagleChirper$Master.$anonfun$hashStartCountInAllFeeds$1$adapted(FinagleChirper.scala:77)                                                                                         at scala.collection.immutable.List.foreach(List.scala:333)
    at org.renaissance.twitter.finagle.FinagleChirper$Master.hashStartCountInAllFeeds(FinagleChirper.scala:77)
    at org.renaissance.twitter.finagle.FinagleChirper$Master.$anonfun$apply$9(FinagleChirper.scala:184)
    at com.twitter.util.Try$.apply(Try.scala:26)
    at com.twitter.util.ExecutorServiceFuturePool$$anon$4.run(FuturePool.scala:163)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)                                                                                                                            
    at java.base/java.lang.Thread.run(Thread.java:833)
```

this happened with darwin-aarch64 c2:
```
[2022-02-22T10:08:13.720+0100] com.twitter.finagle.util.DefaultMonitor (com.twitter.finagle.util.DefaultMonitor logWithRemoteInfo)
WARNING: Exception propagated to the default monitor (upstream address: /127.0.0.1:62480, downstream address: n/a, label: ).

java.util.ConcurrentModificationException: mutation occurred during iteration
        at scala.collection.mutable.MutationTracker$.checkMutations(MutationTracker.scala:43)
        at scala.collection.mutable.CheckedIndexedSeqView$CheckedIterator.hasNext(CheckedIndexedSeqView.scala:47)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
        at org.renaissance.twitter.finagle.FinagleChirper$Master.$anonfun$mostRechirpsInAllFeeds$1(FinagleChirper.scala:112)
        at org.renaissance.twitter.finagle.FinagleChirper$Master.$anonfun$mostRechirpsInAllFeeds$1$adapted(FinagleChirper.scala:110)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1293)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:938)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:97)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:935)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.internal(Tasks.scala:169)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.internal$(Tasks.scala:156)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$AWSFJTWrappedTask.internal(Tasks.scala:304)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.compute(Tasks.scala:149)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.compute$(Tasks.scala:148)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$AWSFJTWrappedTask.compute(Tasks.scala:304)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by lbulej** [comment]
Thank you for the info! The have not really been any changes in the benchmark sources, so this is a bit baffling. Is it limited to the GraalVM or does it happen e.g. on OpenJDK or other VMs?

**Comment by ceresek** [comment]
Possibly also #345 ?

**Comment by farquet** [comment]
This is also observed on GraalVM native image.
Since it's the same as #345, this is very likely to be a benchmark bug that we should look into.
