### ISSUE TITLE
Suspected memory leak in bench Reactors

### ISSUE THREAD

**Issue by dhanalla** [renaissance-benchmarks/renaissance#372]
Encountered the following OOM with java -Xms4G -Xmx4G  -jar renaissance-jmh-0.14.1-10.jar -bm avgt -prof gc -f 1 -t 20 -i 20 Reactors

java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.concurrent.ForkJoinTask.adapt(ForkJoinTask.java:1499)
        at io.reactors.JvmScheduler$ReactorForkJoinWorkerThread.executeLater(JvmScheduler.scala:120)
        at io.reactors.JvmScheduler$ReactorForkJoinWorkerThread.postschedule(JvmScheduler.scala:162)
        at io.reactors.JvmScheduler$Executed.postschedule(JvmScheduler.scala:273)
        at io.reactors.concurrent.Frame.executeBatch(Frame.scala:202)
        at io.reactors.JvmScheduler$Executed$$anon$5.run(JvmScheduler.scala:255)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

memory is held for more than 110 generations. This issue reproduces on Windows & Linux .
![image](https://user-images.githubusercontent.com/45609141/221225256-8a618ac3-0089-4604-b244-3fb805a8f875.png)

**Comment by lbulej** [comment]
Thanks for the report. Can you provide more info on the JDK you were running the benchmark on?
@ceresek did you observe something like that in the long runs?

**Comment by ceresek** [comment]
Our long runs typically used 12G heap (Xms, Xmx) and G1, and never encountered an OOM (with OpenJDK 11 most recently), so this configuration must be different.

**Comment by ceresek** [comment]
Most likely fixed in 0.15.0, please reopen if it happens again ?
