### ISSUE TITLE
CI: ConcurrentModificationException when compiling on JDK10

### ISSUE THREAD

**Issue by vhotspur** [renaissance-benchmarks/renaissance#382]
OpenJDK10 builds are repeatedly failing with the following exception (e.g. in [this run](https://github.com/renaissance-benchmarks/renaissance/actions/runs/4664795277/jobs/8270395019)):

```
Run tools/ci/build-both.sh
  tools/ci/build-both.sh
  shell: bash --noprofile --norc -e -o pipefail {0}
##[debug]bash --noprofile --norc -e -o pipefail /__w/_temp/c34a8479-6b88-4e01-b883-dfa746bb40a5.sh
/__w/renaissance/renaissance /__w/renaissance/renaissance
+ '[' -s target/renaissance-gpl-0.14.2-10-g93f8104.jar ']'
+ ci_sbt --batch 'renaissancePackage;renaissanceJmhPackage'
+ local TRUST_STORE=/__w/renaissance/renaissance/tools/jks/cacerts
+ /__w/renaissance/renaissance/tools/sbt/bin/sbt -J-Djavax.net.ssl.trustStore=/__w/renaissance/renaissance/tools/jks/cacerts --batch 'renaissancePackage;renaissanceJmhPackage'
copying runtime jar...
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1471)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at java.base/jdk.internal.jrtfs.JrtDirectoryStream$1.hasNext(JrtDirectoryStream.java:81)
	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:348)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2752)
	at xsbt.boot.IO.copyDirectory(IO.java:15)
	at xsbt.boot.Launch$.exportRt(Launch.scala:62)
	at xsbt.boot.Launch$.apply(Launch.scala:28)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
Error:  [launcher] error during sbt launcher: java.util.ConcurrentModificationException
[info] [launcher] getting org.scala-sbt sbt 1.6.1  (this may take some time)...
[info] [launcher] getting Scala 2.12.15 (for sbt)...
[info] welcome to sbt 1.6.1 (Oracle Corporation Java 10.0.2)
[info] loading settings for project renaissance-build from build.sbt,plugins.sbt ...
[info] loading project definition from /__w/renaissance/renaissance/project
[info] compiling 14 Java sources to /__w/renaissance/renaissance/renaissance-core/target/scala-2.12/classes ...
[info] done compiling
[info] compiling 4 Scala sources to /__w/renaissance/renaissance/project/target/scala-2.12/sbt-1.0/classes ...
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.15. Compiling...
error: Error while emitting xsbt/ExtractUsedNames$ExtractUsedNamesTraverser
assertion failed: The classfile for xsbt/ExtractUsedNames$ExtractUsedNamesTraverser$PatMatDependencyTraverser$ could not be found on the compilation classpath.
one error found
[info] Attempting to fetch org.scala-sbt:compiler-bridge_2.12:1.6.0.
[error] (Compile / compileIncremental) Error compiling the sbt component 'compiler-bridge_2.12'
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)

Error: Process completed with exit code 1.
##[debug]Finishing: Build base & JMH bundles
```

Unable to reproduce this locally in Podman with the same image.

**Comment by vhotspur** [comment]
This is getting weirder and weirder.

I even tried adding our own packager (see #383) that would create `rt.jar` from the JRT filesystem and this one fails during compilation even.

```text
An exception has occurred in the compiler (10.0.2). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com/) after checking the Bug Database (http://bugs.java.com/) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1471)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at java.base/jdk.internal.jrtfs.JrtDirectoryStream$1.hasNext(JrtDirectoryStream.java:81)
	at jdk.compiler/com.sun.tools.javac.file.JRTIndex.getEntry(JRTIndex.java:210)
	at jdk.compiler/com.sun.tools.javac.file.JRTIndex.getCtSym(JRTIndex.java:185)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.getSupplementaryFlags(ClassFinder.java:250)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:353)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:284)
	at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:633)
	at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1308)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.loadClass(ClassFinder.java:430)
	at jdk.compiler/com.sun.tools.javac.comp.Resolve.loadClass(Resolve.java:1985)
	at jdk.compiler/com.sun.tools.javac.comp.Resolve.findIdentInPackageInternal(Resolve.java:2378)
	at jdk.compiler/com.sun.tools.javac.comp.Resolve.findIdentInPackage(Resolve.java:2366)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.selectSym(Attr.java:3720)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3604)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2110)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:653)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribType(Attr.java:713)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribType(Attr.java:706)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$ImportsPhase.attribImportType(TypeEnter.java:439)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$ImportsPhase.doImport(TypeEnter.java:422)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$ImportsPhase.resolveImports(TypeEnter.java:362)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$ImportsPhase.runPhase(TypeEnter.java:319)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$Phase.doCompleteEnvs(TypeEnter.java:280)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$Phase.completeEnvs(TypeEnter.java:249)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter.complete(TypeEnter.java:198)
	at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:633)
	at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1308)
	at jdk.compiler/com.sun.tools.javac.comp.Enter.complete(Enter.java:583)
	at jdk.compiler/com.sun.tools.javac.comp.Enter.main(Enter.java:560)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:1058)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:929)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:306)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:165)
	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
```

As usual, I am unable to reproduce this locally but it happens quite deterministically on CI.

As a last measure, I will try to use `jimage` to dump the classes and package them manually but it all feels wrong.

**Comment by farquet** [comment]
IMO, any issue that is specific to a JDK that is not LTS or latest isn't worth investigating.
The testing matrix could be updated to be JDK8, JDK11, JDK17 and JDK-latest.

**Comment by vhotspur** [comment]
Closing (see #383, #394, #331).
