### ISSUE TITLE
Spark benchmarks broken by JDK-8296244

### ISSUE THREAD

**Issue by dougxc** [renaissance-benchmarks/renaissance#439]
As a result of [JDK-8296244](https://bugs.openjdk.org/browse/JDK-8296244) some/all Spark benchmarks in renaissance are broken:
```
Benchmark 'als' failed with exception:
java.lang.UnsupportedOperationException: getSubject is supported only if a security manager is allowed
	at java.base/javax.security.auth.Subject.getSubject(Subject.java:347)
	at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:577)
	at org.apache.spark.util.Utils$.$anonfun$getCurrentUserName$1(Utils.scala:2416)
	at scala.Option.getOrElse(Option.scala:201)
	at org.apache.spark.util.Utils$.getCurrentUserName(Utils.scala:2416)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:334)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2888)
	at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:1099)
	at scala.Option.getOrElse(Option.scala:201)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:1093)
	at org.renaissance.apache.spark.SparkUtil.setUpSparkContext(SparkUtil.scala:81)
	at org.renaissance.apache.spark.SparkUtil.setUpSparkContext$(SparkUtil.scala:54)
	at org.renaissance.apache.spark.Als.setUpSparkContext(Als.scala:43)
	at org.renaissance.apache.spark.Als.setUpBeforeAll(Als.scala:88)
	at org.renaissance.harness.ExecutionDriver.executeBenchmark(ExecutionDriver.java:82)
	at org.renaissance.harness.RenaissanceSuite$.runBenchmarks$$anonfun$1(RenaissanceSuite.scala:172)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.renaissance.harness.RenaissanceSuite$.runBenchmarks(RenaissanceSuite.scala:205)
	at org.renaissance.harness.RenaissanceSuite$.main(RenaissanceSuite.scala:130)
	at org.renaissance.harness.RenaissanceSuite.main(RenaissanceSuite.scala)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.renaissance.core.Launcher.loadAndInvokeHarnessClass(Launcher.java:129)
	at org.renaissance.core.Launcher.launchHarnessClass(Launcher.java:78)
	at org.renaissance.core.Launcher.main(Launcher.java:43)
```

As far as I can see, any app that does not explicitly set the java.security.manager system property can [no longer call](https://github.com/openjdk/jdk/blob/e06b568c3c645dc9bb3d3e601e5429bb6a9b31f1/src/java.base/share/classes/javax/security/auth/Subject.java#L346-L349) `javax.security.auth.Subject.getSubject()`.

**Comment by dougxc** [comment]
I'm not aware of any particular guide apart from deprecation warnings that more recent versions of javac must be emitting when compiling Spark code that used deprecated API.

It might be worth encouraging Spark maintainers to periodically look at these warnings and plan for addressing them.

**Comment by AlanBateman** [comment]
Just to add to Weijun's comment. Subject.getSubject(ACC) has deprecated for removal since Java 17. Developers are encouraged to move to the replacement Subject.current(). I think we should make sure there is an issue n the Hadoop issue tracker for this.

**Comment by lbulej** [comment]
> The `Subject::getSubject` method takes an `AccessControlContext` argument and it will be non-functional after Security Manager is removed. JDK-8296244 is meant to provide an alternative implementation so users can experience it right now. Please read the [CSR](https://bugs.openjdk.org/browse/JDK-8327134) and the [Release Note](https://bugs.openjdk.org/browse/JDK-8328643)(not delivered yet) for more details.

Thanks for the links!

> You can try the `Subject::current` method and see if it works for you, or, as a workaround, add `-Djava.security.manager=allow` to keep the old behavior.

Great! This might be just what's needed for Renaissance. I'll check if we can setup the right environment for Spark in the harness so that its calls to Hadoop do not fail on this.

**Comment by AlanBateman** [comment]
I've created [HADOOP-19212](https://issues.apache.org/jira/browse/HADOOP-19212) in the Hadoop issue tracker.

**Comment by lbulej** [comment]
As far as I can see, there is no way to fix this from inside the Renaissance harness apart from spawning a child process. This is what shell is good for, so at the moment the only option is to just add `-Djava.security.manager=allow` to the command line.

There are several components call `UserGroupInformation.getCurrentUser()` (they might be happy with getting the current user name), which will end up calling `Subject.getSubject()`. Some calls into UGI can be avoided, e.g., setting the `SPARK_USER` environment variable (impossible from inside the harness except through ugly reflection tricks) allows moving a little past creating the initial Spark context, only to crash on the next one.

Both Hadoop 3.4.0 and 3.3.6 fail on this and HADOOP-19212 issue is without any response..

**Comment by AlanBateman** [comment]
There will be a JEP to remove the SecurityManager implementation. When that comes then running with `-Djava.security.manager=allow` will be an error at startup. Moving toward will require code using the terminally deprecated `Subject.getSubject(AccessControlContext)` to move to the replacement API (Subject.current) or use something else. For this Renaissance benchmark then it will HADOOP-19212 be addressed, maybe someone familiar with that code could propose a patch to help that project move away from the API that is marked for removal since JDK 17.

**Comment by MBaesken** [comment]
While with JDK23 the suggested workaround (`-Djava.security.manager=allow` ) was still useable, with JDK24ea it got worse, I run into this error when trying to run als with the workaround 
Error occurred during initialization of VM
java.lang.Error: A command line option has attempted to allow or enable the Security Manager. Enabling a Security Manager is not supported.
        at java.lang.System.initPhase3(java.base@24-ea/System.java:2070)

**Comment by AlanBateman** [comment]
There is some activity in [HADOOP-19212](https://issues.apache.org/jira/browse/HADOOP-19212) and a PR in progress.
